name: FirstWorkflow

on:
  push:
    branch: 
      - main
jobs:
  sampleworkflow:
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: run list of files
        run: ls -l 
