name: FirstWorkflow

on:
  push:
    branches: 
      - main
jobs:
  sampleworkflow:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: run list of files
        run: ls -l 
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: repo-file-list
          path: .
          retention-days: 7 # optional
  
  wait-job:
    needs: sampleworkflow
    runs-on: ubuntu-latest
    steps:
      - name: sleep 10 After sampleworkflow completes
        run: sleep 10
  
  runner-name:
    needs: wait-job
    runs-on: ubuntu-latest
    steps:
      - run: uname -a
      - run: echo "Running on $RUNNER_OS"

  date-job:
    needs: runner-name 
    runs-on: ubuntu-latest
    steps:
      - name: show date
        run: date

  pwd-job:
    needs: runner-name
    runs-on: ubuntu-latest
    steps:
      - name: Print working directory
        run : pwd

  demo:
    needs: runner-name
    runs-on: ubuntu-latest
    env:
      APP_ENV: dev
    steps:
      - name: Print APP_ENV variable
        run: echo "ENVIRONMENT: $APP_ENV"
     
     
