name: FirstWorkflow

on:
  push:
    branches: 
      - main
jobs:
  sampleworkflow:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: run list of files
        run: ls -l 
  runner-name:
    needs: sampleworkflow
    runs-on: ubuntu-latest
    steps:
      - run: uname -a
      - run: echo "Running on $RUNNER_OS"
     
